### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'uptime'

### ISSUE THREAD

**Issue by aphex3k** [mawoka-myblock/uptime-kuma-static#1]
I'm using uptime-kuma version 1.12.1

I'm getting nothing but errors when running the docker image:

```python
future: <Task finished name='Task-29' coro=<AsyncClient._handle_eio_message() done, defined at /usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py:488> exception=UndefinedError("'dict object' has no attribute 'uptime'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 505, in _handle_eio_message
    await self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 372, in _handle_event
    r = await self._trigger_event(data[0], namespace, *data[1:])
  File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 424, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/app/main.py", line 63, in uptime
    await write_template()
  File "/app/main.py", line 25, in write_template
    await f.write(await template.render_async(mons=mons, analytics=config_analytics_enabled))
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1325, in render_async
    return self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1323, in <listcomp>
    return concat([n async for n in self.root_render_func(ctx)])  # type: ignore
  File "<template>", line 19, in top-level template code
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'uptime'
Task exception was never retrieved
future: <Task finished name='Task-31' coro=<AsyncClient._handle_eio_message() done, defined at /usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py:488> exception=UndefinedError("'dict object' has no attribute 'uptime'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 505, in _handle_eio_message
    await self._handle_event(pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 372, in _handle_event
    r = await self._trigger_event(data[0], namespace, *data[1:])
  File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 424, in _trigger_event
    ret = await self.handlers[namespace][event](*args)
  File "/app/main.py", line 63, in uptime
    await write_template()
  File "/app/main.py", line 25, in write_template
    await f.write(await template.render_async(mons=mons, analytics=config_analytics_enabled))
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1325, in render_async
    return self.environment.handle_exception()
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1323, in <listcomp>
    return concat([n async for n in self.root_render_func(ctx)])  # type: ignore
  File "<template>", line 19, in top-level template code
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 455, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'uptime'
packet queue is empty, aborting
connection established
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6fd6f45220>
Exception ignored in: <function ClientResponse.__del__ at 0x7f6fd728ff70>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 803, in __del__
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 170, in release
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 650, in _release
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_proto.py", line 63, in close
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 700, in close
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<stop_after_10() done, defined at /app/main.py:33> exception=SystemExit()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/app/main.py", line 35, in stop_after_10
    sys.exit()
SystemExit
```

**Comment by mawoka-myblock** [comment]
> I'm using uptime-kuma version 1.12.1
> 
> I'm getting nothing but errors when running the docker image:
> 
> ```python
> future: <Task finished name='Task-29' coro=<AsyncClient._handle_eio_message() done, defined at /usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py:488> exception=UndefinedError("'dict object' has no attribute 'uptime'")>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 505, in _handle_eio_message
>     await self._handle_event(pkt.namespace, pkt.id, pkt.data)
>   File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 372, in _handle_event
>     r = await self._trigger_event(data[0], namespace, *data[1:])
>   File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 424, in _trigger_event
>     ret = await self.handlers[namespace][event](*args)
>   File "/app/main.py", line 63, in uptime
>     await write_template()
>   File "/app/main.py", line 25, in write_template
>     await f.write(await template.render_async(mons=mons, analytics=config_analytics_enabled))
>   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1325, in render_async
>     return self.environment.handle_exception()
>   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
>     raise rewrite_traceback_stack(source=source)
>   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1323, in <listcomp>
>     return concat([n async for n in self.root_render_func(ctx)])  # type: ignore
>   File "<template>", line 19, in top-level template code
>   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 455, in getitem
>     return obj[argument]
> jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'uptime'
> Task exception was never retrieved
> future: <Task finished name='Task-31' coro=<AsyncClient._handle_eio_message() done, defined at /usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py:488> exception=UndefinedError("'dict object' has no attribute 'uptime'")>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 505, in _handle_eio_message
>     await self._handle_event(pkt.namespace, pkt.id, pkt.data)
>   File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 372, in _handle_event
>     r = await self._trigger_event(data[0], namespace, *data[1:])
>   File "/usr/local/lib/python3.9/site-packages/socketio/asyncio_client.py", line 424, in _trigger_event
>     ret = await self.handlers[namespace][event](*args)
>   File "/app/main.py", line 63, in uptime
>     await write_template()
>   File "/app/main.py", line 25, in write_template
>     await f.write(await template.render_async(mons=mons, analytics=config_analytics_enabled))
>   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1325, in render_async
>     return self.environment.handle_exception()
>   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
>     raise rewrite_traceback_stack(source=source)
>   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 1323, in <listcomp>
>     return concat([n async for n in self.root_render_func(ctx)])  # type: ignore
>   File "<template>", line 19, in top-level template code
>   File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 455, in getitem
>     return obj[argument]
> jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'uptime'
> packet queue is empty, aborting
> connection established
> Unclosed client session
> client_session: <aiohttp.client.ClientSession object at 0x7f6fd6f45220>
> Exception ignored in: <function ClientResponse.__del__ at 0x7f6fd728ff70>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 803, in __del__
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 170, in release
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 650, in _release
>   File "/usr/local/lib/python3.9/site-packages/aiohttp/client_proto.py", line 63, in close
>   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 700, in close
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
> RuntimeError: Event loop is closed
> Task exception was never retrieved
> future: <Task finished name='Task-2' coro=<stop_after_10() done, defined at /app/main.py:33> exception=SystemExit()>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
>     self.run_forever()
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
>     self._run_once()
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
>     handle._run()
>   File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "/app/main.py", line 35, in stop_after_10
>     sys.exit()
> SystemExit
> ```

I'll have a look at it in the next days! Thank you for opening this issue!

**Comment by mawoka-myblock** [comment]
Would it be ok for you, if the docker-image wouldn't have a cron built-in, so you would have to set up a cron on your host-machine?

**Comment by mawoka-myblock** [comment]
Should be fixed, because I removed the cron in the docker-container. Please let me know, if it is also fixed for you!

**Comment by aphex3k** [comment]
> Would it be ok for you, if the docker-image wouldn't have a cron built-in, so you would have to set up a cron on your host-machine?

I personally would actually prefer that behavior :) as it allows for better resource planning on the docker host.

> Should be fixed, because I removed the cron in the docker-container. Please let me know, if it is also fixed for you!

I will give it a try on the weekend and let you know

**Comment by mawoka-myblock** [comment]
> > Would it be ok for you, if the docker-image wouldn't have a cron built-in, so you would have to set up a cron on your host-machine?
> 
> I personally would actually prefer that behavior :) as it allows for better resource planning on the docker host.
> 
> > Should be fixed, because I removed the cron in the docker-container. Please let me know, if it is also fixed for you!
> 
> I will give it a try on the weekend and let you know

OK, I've updated the docker-image!

**Comment by mawoka-myblock** [comment]
Is it fixed for you, @aphex3k ?

**Comment by mawoka-myblock** [comment]
I'll close it, since I get no response.
